version: '3.7'
services:
  servicereg:
    image: dimebag60/servicereg:latest
    container_name: servicereg
    ports:
      - "8761:8761"
    depends_on:
      - rabbitmq
    networks:
      - microservice-network

  accountms:
    image: dimebag60/account
    container_name: account
    ports:
      - 8081:8081
    depends_on:
      - servicereg
    networks:
      - microservice-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  clientms:
    image: dimebag60/client
    container_name: client
    ports:
      - 8080:8080
    depends_on:
      - servicereg
    networks:
      - microservice-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://servicereg:8761/eureka

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge